In [1]:
import numpy as np

In [2]:
l=[1,2,3]

In [3]:
n=np.array(l)

In [4]:
type(n)

numpy.ndarray

In [5]:
n.dtype

dtype('int64')

In [6]:
n.ndim

1

In [7]:
n.size

3

In [8]:
n.shape

(3,)

In [9]:
l1=[[1,2,3],[4,5,6]]

In [10]:
a=np.array(l1)

In [11]:
type(a)

numpy.ndarray

In [12]:
a.dtype

dtype('int64')

In [13]:
a.ndim

2

In [14]:
a.size

6

In [15]:
a.shape

(2, 3)

In [16]:
m=np.matrix(a)

In [17]:
shallow=m #shallow copy

In [18]:
m[0,0]=5

In [19]:
m

matrix([[5, 2, 3],
        [4, 5, 6]])

In [20]:
shallow

matrix([[5, 2, 3],
        [4, 5, 6]])

In [21]:
deep=np.copy(m)  #deep copy

In [22]:
deep[0,0]=45

In [23]:
deep

array([[45,  2,  3],
       [ 4,  5,  6]])

In [24]:
m

matrix([[5, 2, 3],
        [4, 5, 6]])

In [25]:
np.fromfunction(lambda i, j : i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [26]:
np.fromfunction(lambda i, j : i*j , (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [27]:
np.fromiter((i for i in range(5)), dtype=int)

array([0, 1, 2, 3, 4])

In [28]:
np.fromstring("54 78", sep=" ", dtype=int)

array([54, 78])

In [29]:
# list(range(1.5, 2.5, 0.1))

In [30]:
np.arange(1.5, 2.5, 0.1)

array([1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4])

In [33]:
np.linspace(2,4,10)

array([2.        , 2.22222222, 2.44444444, 2.66666667, 2.88888889,
       3.11111111, 3.33333333, 3.55555556, 3.77777778, 4.        ])

In [39]:
np.eye(3,3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [48]:
arr1=np.zeros((3,3), dtype=int)

In [52]:
arr1+5

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [53]:
arr2=np.ones((3,3), dtype=int)

In [54]:
arr2*5

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [70]:
np.random.rand(3,3)

array([[0.31772244, 0.97465399, 0.10953109],
       [0.43793528, 0.14240861, 0.39752372],
       [0.59145509, 0.01946023, 0.27056684]])

In [95]:
np.random.randn(3,3)  #mean=0, std=1

array([[-0.60322609, -1.29541052, -0.05313747],
       [ 0.52868037, -0.88776743, -0.43378138],
       [ 0.34987955,  0.3282397 , -1.86223062]])

In [15]:
arr=np.random.randint(1,5 ,(3,4))

In [16]:
arr

array([[2, 1, 2, 1],
       [2, 4, 4, 3],
       [2, 1, 1, 2]])

In [17]:
arr.reshape(4,3)

array([[2, 1, 2],
       [1, 2, 4],
       [4, 3, 2],
       [1, 1, 2]])

In [18]:
arr

array([[2, 1, 2, 1],
       [2, 4, 4, 3],
       [2, 1, 1, 2]])

In [19]:
arr[1][1]

4

In [20]:
arr[1:3,2:4]

array([[4, 3],
       [1, 2]])

In [21]:
arr[1][2]=3

In [22]:
arr

array([[2, 1, 2, 1],
       [2, 4, 3, 3],
       [2, 1, 1, 2]])

In [26]:
arr[arr<3]

array([2, 1, 2, 1, 2, 2, 1, 1, 2])

In [97]:
arr1=np.random.randint(1,3,(3,3))

In [98]:
arr2=np.random.randint(1,3,(3,3))

In [99]:
arr1

array([[1, 1, 1],
       [1, 2, 2],
       [2, 2, 1]])

In [100]:
arr2

array([[1, 2, 2],
       [1, 1, 1],
       [1, 1, 2]])

In [101]:
arr1+arr2  #index-wise operation

array([[2, 3, 3],
       [2, 3, 3],
       [3, 3, 3]])

In [102]:
arr1@arr2   #matrix-wise operation

array([[3, 4, 5],
       [5, 6, 8],
       [5, 7, 8]])

In [103]:
arr1**arr2

array([[1, 1, 1],
       [1, 2, 2],
       [2, 2, 1]])

In [18]:
arr1+2

array([[3, 4, 3],
       [4, 4, 3],
       [3, 4, 4]])

In [19]:
arr=np.zeros((3,3), dtype=int)

In [20]:
row=np.array([1,2,3])

In [21]:
arr+row

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [22]:
col=row.reshape(3,1)

In [23]:
col

array([[1],
       [2],
       [3]])

In [24]:
col+arr

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [25]:
np.square(arr1)

array([[1, 4, 1],
       [4, 4, 1],
       [1, 4, 4]])

In [26]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.        ],
       [1.41421356, 1.41421356, 1.        ],
       [1.        , 1.41421356, 1.41421356]])

In [39]:
arr=np.array([1,2,3,4])

In [88]:
np.repeat(arr,2)

array([5, 5, 7, 7, 1, 1, 3, 3])

In [89]:
np.expand_dims(arr, axis=0)

array([[5, 7, 1, 3]])

In [90]:
np.expand_dims(arr, axis=1)

array([[5],
       [7],
       [1],
       [3]])

In [91]:
arr=np.array([[1],[2],[3]])

In [92]:
np.squeeze(a)

array([1, 2, 3])

In [93]:
arr=np.array([5,7,1,3])

In [94]:
np.roll(arr,2)

array([1, 3, 5, 7])

In [95]:
np.diag(arr)

array([[5, 0, 0, 0],
       [0, 7, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 3]])

In [104]:
#string functions

In [105]:
arr=np.array(["ShirY","kisHor"])

In [107]:
np.char.upper(arr)

array(['SHIRY', 'KISHOR'], dtype='<U6')

In [108]:
np.char.lower(arr)

array(['shiry', 'kishor'], dtype='<U6')

In [109]:
np.char.capitalize(arr)

array(['Shiry', 'Kishor'], dtype='<U6')

In [110]:
arr=np.random.randint(1,9,(3,3))

In [111]:
arr

array([[2, 3, 4],
       [4, 1, 5],
       [3, 6, 1]])

In [112]:
np.sin(arr)

array([[ 0.90929743,  0.14112001, -0.7568025 ],
       [-0.7568025 ,  0.84147098, -0.95892427],
       [ 0.14112001, -0.2794155 ,  0.84147098]])

In [113]:
np.cos(arr)

array([[-0.41614684, -0.9899925 , -0.65364362],
       [-0.65364362,  0.54030231,  0.28366219],
       [-0.9899925 ,  0.96017029,  0.54030231]])

In [114]:
np.tan(arr)

array([[-2.18503986, -0.14254654,  1.15782128],
       [ 1.15782128,  1.55740772, -3.38051501],
       [-0.14254654, -0.29100619,  1.55740772]])

In [115]:
np.power(arr,2)

array([[ 4,  9, 16],
       [16,  1, 25],
       [ 9, 36,  1]])

In [116]:
np.sqrt(arr)

array([[1.41421356, 1.73205081, 2.        ],
       [2.        , 1.        , 2.23606798],
       [1.73205081, 2.44948974, 1.        ]])

In [117]:
np.mean(arr)

3.2222222222222223

In [123]:
np.median(arr)

3.0

In [120]:
np.std(arr)

1.617802197617893

In [121]:
np.min(arr)

1

In [134]:
arr.max()

9

In [125]:
arr=np.random.randint(0,10,15)

In [126]:
arr

array([8, 0, 7, 6, 3, 1, 7, 8, 5, 3, 2, 1, 1, 9, 7])

In [127]:
np.count_nonzero(arr)

14

In [131]:
np.where(arr>7)

(array([ 0,  7, 13]),)

In [133]:
np.extract(arr>7, arr)

array([8, 8, 9])

In [135]:
arr

array([8, 0, 7, 6, 3, 1, 7, 8, 5, 3, 2, 1, 1, 9, 7])

In [136]:
a=arr.copy()  #deep copy

In [138]:
a[0]=1

In [139]:
a

array([1, 0, 7, 6, 3, 1, 7, 8, 5, 3, 2, 1, 1, 9, 7])

In [140]:
arr

array([8, 0, 7, 6, 3, 1, 7, 8, 5, 3, 2, 1, 1, 9, 7])

In [141]:
b=arr.view()  #shallow copy

In [142]:
b[0]=2

In [143]:
b

array([2, 0, 7, 6, 3, 1, 7, 8, 5, 3, 2, 1, 1, 9, 7])

In [144]:
arr

array([2, 0, 7, 6, 3, 1, 7, 8, 5, 3, 2, 1, 1, 9, 7])

In [147]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [149]:
np.dot(a,b)  #matrix multiplication

380

In [152]:
a@b   #matrix multiplication

380